[versions]
agp = "8.12.3"
ksp = "1.9.22-1.0.17"

# Firebase
firebaseBom = "34.2.0"
firebaseMessaging = "25.0.0"

# JSON & Networking
glide = "4.16.0"
gson = "2.11.0"
retrofit = "2.11.0"
okhttp = "5.1.0"


# AndroidX & UI
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
annotation = "1.6.0"

# Lifecycle
lifecycle = "2.8.7"

# Location
playServicesLocation = "21.3.0"

# WebSocket
javaWebsocket = "1.5.6"

# Testing
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"


[libraries]
# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

# JSON & Networking
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# AndroidX & UI
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

# Lifecycle
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }

# Location
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

# WebSocket
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
